export const TOOLS_NAMES = {
  T25_DAY_AHEAD_TOOL: 'T25_dayahead',
  T25_REAL_TIME_TOOL: 'T25_realtime',
  T41_WIND_AND_PV: 'T41_windpv',
  T41_STOCHASTIC_MP_ACOPF: 'T41_stochasticmp',
  T41_TRACTABILITY: 'T41_Tractability_Tool',
  T26_MARKET_SIMUL: 'T26_marketSimul',
  T31_OPT_TOOL_DX: 'T31_optToolDx',
  T32_OPT_TOOL_TX: 'T32_optToolTx',
  T33_OPT_TOOL_PLAN_TSO_DSO: 'T33_optToolPlanTsoDso',
  T42_AS_REAL_TIME_DX: 'T42_asRealTimeDx',
  T43_STATE_ESTIMATOR: 'T43_stateEstimator',
  T44_AS_DAY_HEAD_TX: 'T44_asDayheadTx',
  T45_AS_REAL_TIME_DX: 'T42_asRealTimeDx',
  T46_ODSA: 'T46_odsa',
  T51_CHARACTERIZATION: 'T51_characterization',
  T51_MONITORING: 'T51_monitoring',
  T52_INDICATOR: 'T52_indicator',
  T53_MANAGEMENT: 'T53_management',
};

export const TOOLS_INFO = {
  T25_DAY_AHEAD_TOOL: { name: 'T25_dayahead', path: '/tools/t25-dayahead' },
  T25_REAL_TIME_TOOL: { name: 'T25_realtime', path: '/tools/t25-realtime' },
  T41_WIND_AND_PV: { name: 'T41_windpv', path: '/tools/sgt' },
  T41_STOCHASTIC_MP_ACOPF: { name: 'T41_stochasticmp', path: '' },
  T41_TRACTABILITY: { name: 'T41_Tractability_Tool', path: '/tools/t41' },
  T26_MARKET_SIMUL: { name: 'T26_marketSimul', path: '' },
  T31_OPT_TOOL_DX: { name: 'T31_optToolDx', path: '' },
  T32_OPT_TOOL_TX: { name: 'T32_optToolTx', path: '' },
  T33_OPT_TOOL_PLAN_TSO_DSO: { name: 'T33_optToolPlanTsoDso', path: '' },
  T42_AS_REAL_TIME_DX: { name: 'T42_asRealTimeDx', path: '' },
  T43_STATE_ESTIMATOR: { name: 'T43_stateEstimator', path: '' },
  T44_AS_DAY_HEAD_TX: { name: 'T44_asDayheadTx', path: '/tools/t44' },
  T45_AS_REAL_TIME_DX: { name: 'T42_asRealTimeDx', path: '' },
  T46_ODSA: { name: 'T46_odsa', path: '' },
  T51_CHARACTERIZATION: { name: 'T51_characterization', path: '' },
  T51_MONITORING: { name: 'T51_monitoring', path: '/tools/t51' },
  T52_INDICATOR: { name: 'T52_indicator', path: '' },
  T53_MANAGEMENT: { name: 'T53_management', path: '' },
};
