import React from 'react';
import { useAppDispatch, useAppSelector } from 'app/config/store';
import { FormProvider, useForm } from 'react-hook-form';
import { Link } from 'react-router-dom';
import { toast } from 'react-toastify';
import { Button, Form, Modal, ModalBody, ModalFooter, ModalHeader } from 'reactstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import Divider from 'app/shared/components/divider/divider';
import LoadingOverlay from 'app/shared/components/loading-overlay/loading-overlay';
import { SELECTION_TYPE } from 'app/shared/components/network-search/constants/constants';
import NetworkInfo from 'app/shared/components/network-info/network-info';
import ToolResultsSearch from 'app/shared/components/tool-results-search/tool-results-search';

import { TOOLS_INFO } from 'app/modules/tools/info/tools-names';
import { WP_IMAGE } from 'app/modules/tools/info/tools-info';

import { runTool, reset as retry } from 'app/modules/tools/reducer/tools-execution.reducer';
import { downloadResults } from 'app/modules/tools/WP4/reducer/tools-results.reducer';
import { T42DefaultParameters } from 'app/modules/tools/WP4/T42/parameters/default-parameters';
import Auxiliary from 'app/modules/tools/WP4/T42/config/auxiliary/auxiliary';
import { defaultValue as ToolResultDefaultValue, IToolResult } from 'app/shared/model/tool-results.model';
import { pathButton } from 'app/shared/reducers/back-button-path';

import ModalConfirmToolExecution from 'app/shared/components/tool-confirm-execution/modal-tool-confirm-execution';
import ToolTitle from 'app/shared/components/tool-title/tool-title';
import { RUN_TOOL_START, RUN_TOOL_FAILURE } from 'app/shared/util/toast-msg-constants';

const T42Config = (props: any) => {
  const { toolNum, title, toolName, resultsPath, additionalNetwork, parameters } = props;

  const divRef = React.useRef<HTMLDivElement>();

  // --- info used to identify output file generated by T41 used by T42
  const DAToolNum = 'T41';
  const t41FileNameKeys = ['_output']; // T41 output file must contains this keyword

  const dispatch = useAppDispatch();
  const methods = useForm({ defaultValues: { parameters: { ...T42DefaultParameters } } });
  const { handleSubmit, reset } = methods;
  const network = props.location.network || JSON.parse(sessionStorage.getItem('network'));

  if (!network) {
    props.history?.goBack();
    return;
  }

  const [openOffCanvas, setOpenOffCanvas] = React.useState<boolean>(false);
  const [openModal, setOpenModal] = React.useState<boolean>(false);
  const [form, setForm] = React.useState(null);
  const [showBtnGoToTask, setShowBtnGoToTask] = React.useState<boolean>(false);

  const loading = useAppSelector(state => state.toolsExecution.loading);
  const response = useAppSelector(state => state.toolsExecution.entity);
  const completed = useAppSelector(state => state.toolsExecution.updateSuccess);

  const [toolResults, setToolResults] = React.useState<IToolResult[]>(null);
  const setToolResultsCallback = (n: IToolResult[]) => setToolResults(n);
  const [enableUploadT41Results, setEnableUploadT41Results] = React.useState<boolean>(true); // if true the user must upload t41 output file's results

  // -- Manage T41's output results selection.
  React.useEffect(() => {
    toolResults && toolResults.length > 0 ? setEnableUploadT41Results(false) : setEnableUploadT41Results(true);
  }, [toolResults]);

  const convertBooleanToString = React.useCallback((value: boolean) => {
    return value ? '1' : '0';
  }, []);

  const submitMethod = data => {
    const finalForm = {
      networkId: network.id,
      toolName,
      ...(data.parameters && { parameterNames: [...Object.keys(data.parameters)] }),
      ...(data.parameters && {
        parameterValues: [
          ...Object.values(data.parameters).map(param => (typeof param === 'boolean' ? convertBooleanToString(param) : param)),
        ],
      }),
      ...(data.profiles?.length > 0 ? { profileIds: [...data.profiles.map(profile => profile.id)] } : {}),
      ...(toolResults?.length > 0 ? { otherToolOutputFileIds: [...toolResults.map(tr => tr.outputFileId)] } : {}),
      filesDesc: [
        ...(data.additionalNetwork?.length > 0 ? ['additionalNetwork'] : []),
        ...Object.keys(data.auxiliary).filter(key => data.auxiliary[key].length > 0),
      ],
      files: [
        ...(data.additionalNetwork?.length > 0 ? data.additionalNetwork : []),
        ...Object.values(data.auxiliary)
          .filter(files => files[0] !== undefined)
          .map(files => files[0]),
      ],
    };
    setForm({ ...finalForm });
    /* eslint-disable-next-line no-console */
    console.log('T42 finalForm ', finalForm);
    setOpenModal(true);
  };

  const checkAndRun = () => {
    /* eslint-disable-next-line no-console */
    console.log('T42 checkAndRun()');
    setOpenModal(false);
    setTimeout(() => {
      dispatch(
        runTool({
          networkId: form.networkId,
          toolName: form.toolName,
          filesDesc: form.filesDesc,
          files: form.files,
          parameterNames: form.parameterNames || [],
          parameterValues: form.parameterValues || [],
          ...(form.profileIds && { profileIds: form.profileIds }),
          ...(form.otherToolOutputFileIds && { otherToolOutputFileIds: form.otherToolOutputFileIds }),
        })
      )
        .unwrap()
        .then(res => {
          if (res.data.status === 'ko') {
            toast.error(toolNum + ': ' + RUN_TOOL_FAILURE);
          } else {
            toast.success(toolNum + ': ' + RUN_TOOL_START);
            setShowBtnGoToTask(true);
          }
        })
        .catch(err => {
          /* eslint-disable-next-line no-console */
          console.error(err);
        });
    }, 500);
  };

  const checkCompleted = () => {
    return completed && response.args?.toolName === toolName;
  };

  const checkCompletedWithError = () => {
    return completed && response.args?.toolName === toolName && response.status === 'ko';
  };

  return (
    <div ref={divRef}>
      {loading && <LoadingOverlay ref={divRef} />}

      <ToolTitle imageAlt={WP_IMAGE.WP4.alt} title={title} imageSrc={WP_IMAGE.WP4.src} />

      <Divider />
      {network && (
        <>
          <NetworkInfo network={network} />

          <Divider />

          {/* Section allowing selection of results obtained from simulations launched with other tools e.g. T41 */}
          <ToolResultsSearch
            network={network}
            setRowsSelectedCallback={setToolResultsCallback}
            selectionType={SELECTION_TYPE.SINGLE}
            toolNum={DAToolNum}
            filtersBy={t41FileNameKeys}
          />

          <Divider />

          <FormProvider {...methods}>
            <Form onSubmit={handleSubmit(submitMethod)}>
              {additionalNetwork}
              <Divider />

              {parameters}
              <Divider />

              {/* Section for uploading Auxiliary Files */}
              <Auxiliary enableUploadOtherToolResults={enableUploadT41Results} resultsSelected={toolResults} />

              <Divider />
              <div style={{ float: 'right' }}>
                {!showBtnGoToTask ? (
                  <>
                    <Button color="primary" onClick={() => reset()}>
                      <FontAwesomeIcon icon="redo" />
                      {' Reset'}
                    </Button>{' '}
                    <Button color="primary" type="submit">
                      <FontAwesomeIcon icon="play" />
                      {' Run '}
                    </Button>
                  </>
                ) : (
                  <>
                    <Button tag={Link} to={'/task'} color="success">
                      <FontAwesomeIcon icon="poll" />
                      {' Go to Tasks '}
                    </Button>{' '}
                  </>
                )}
              </div>
            </Form>
          </FormProvider>
        </>
      )}
      <Divider />
      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <Button tag={Link} to="/tools" color="info">
          <FontAwesomeIcon icon="arrow-left" />
          {' Back'}
        </Button>
      </div>
      {form && (
        <ModalConfirmToolExecution
          toolDescription={title}
          form={form}
          openModal={openModal}
          checkAndRun={checkAndRun}
          setOpenModal={setOpenModal}
        />
      )}
    </div>
  );
};

export default T42Config;
